import streamlit as st

st.markdown("# ini adalah contoh heading H1")
st.markdown("## ini adalah contoh heading H2")
st.markdown("### ini adalah contoh heading H3")
st.markdown("Ini tulisan **Bold** :star:")
st.markdown("Ini tulisan *Italic* :star:")
st.markdown("> Block")
st.markdown("1. Nasi Goreng")
st.markdown("2. Goreng Nasi")
st.markdown("3. Nasi di Goreng")
st.markdown("- Item kesatu")
st.markdown("- Ini kedua")
st.markdown("- Ini ketiga")
st.markdown("Ini kode `st.markdown`")
st.markdown("---")
st.write("Diatas adalah Horizontal Rule")

st.title("Praktikum Aplikasi WEB :smile: :smile:")
st.header("Ini adalah latihan saya :rocket: ")
st.subheader("Prodi Teknologi Informasi")
st.caption("Departemen Pendidikan Teknik Elektronika dab Informatika")
st.text("Saya kuliah sejak tahun 2022")
st.write("NIM saya 22537144001")